### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-footer-services bundle size difference from 3.0.1 to ccb78464fec5b1d2b3dff62baf5ac41e1353e777
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-footer-services bundle size difference from 3.0.1 to 49f9ac8b6b70fb3144e798a33c2ae6d8402e9d02
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-footer-services bundle size difference from 3.0.1 to 0aa55c089721130e4513a8863faac9997476b9af
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-footer-services bundle size difference from 3.0.1 to 30aaef812e5f2cd64a8ddbc57be473e5b7afdcb7
No significant bundle size differences found.

**Pull request merged**
