### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by notlee**
https://github.com/Financial-Times/o-footer-services/issues/29

### CODE REVIEW

**Comment by notlee** [comment]
Addresses:
https://github.com/Financial-Times/o-footer-services/issues/10
https://github.com/Financial-Times/o-footer-services/issues/22
https://github.com/Financial-Times/o-footer-services/issues/23

**Comment by origamiserviceuser** [comment]
o-footer-services bundle size difference from 2.2.0 to fc7b6a487a1e0ba365a878c81c38da3d124493b6
No bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-footer-services bundle size difference from 2.2.0 to 971f07ac1c5ad5201f5456b1623531b6c6638107
css, master: 1.15kb increase (0.11kb/gzip)
css, internal: 1.14kb increase (0.11kb/gzip)
css, whitelabel: 1.2kb increase (0.13kb/gzip)

**Comment by origamiserviceuser** [comment]
o-footer-services bundle size difference from 2.2.0 to a32522fcb1b645bf048164c92f673ca52d4d286c
css, master: 1.11kb increase (0.10kb/gzip)
css, internal: 1.1kb increase (0.10kb/gzip)
css, whitelabel: 1.16kb increase (0.12kb/gzip)

**Comment by notlee** [comment]
This was reviewed in previous PRs

**Pull request merged**
